const HTB_DATA = [
  {
    id: 1,
    sectionHTB: "Incident Handling",
    sentenceHTB: "Incident handling is a clearly defined set of procedures for managing and responding to security incidents in a computer or network environment.",
    modul: "Angewandte Incident Response und IT Forensik (IRFORENSIC)",
    modulCode: "IRFORENSIC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Wissen wie bei einem Incident vorzugehen ist; Analysemöglichkeiten zum Auffinden des Angreifers",
    methodenkompetenzen: "Analytisches Vorgehen, um Angreifer in Systemen zu finden; Einleiten von Massnahmen, um Angreifer auszusperren; Effizienter Einsatz von Tools",
    personalkompetenz: "Analytisches und Systematisches Vorgehen",
    modulkurzbeschrieb: "Hacker benutzen ausgefeilte Techniken, um in Systeme einzudringen und diese zu kompromittieren. Die Reaktion, die Identifizierung sowie das Sicherstellen von Beweisen ist elementar.",
    agenda: "SW 1 Einführung: Incident Management, Incident Response"
  },
  {
    id: 2,
    sectionHTB: "Cyber Kill Chain",
    sentenceHTB: "The cyber kill chain consists of seven different stages... Recon, Weaponize, Deliver, Exploit, Install, C&C, Action.",
    modul: "Cyber Defence (CYBER)",
    modulCode: "CYBER",
    abschlusskompetenzen: "",
    fachkompetenzen: "Information Gathering selbständig durchführen; Scanning selbständig durchführen; Angriff und Foothold selbständig durchführen",
    methodenkompetenzen: "Cyber-Kill Chain anwenden",
    personalkompetenz: "Verantwortungsvoller Umgang im Cyberspace",
    modulkurzbeschrieb: "Im Modul \"Cyber\" konzentrieren wir uns auf die grundlegenden Aspekte des ethischen Hackings entlang der Cyber-Kill Chain.",
    agenda: "SW 5 Kill Chain: Cyber Kill Chain, Rootkits, Penetration Testing Report"
  },
  {
    id: 3,
    sectionHTB: "Incident Handling Process Overview",
    sentenceHTB: "The Incident Handling Process defines a capability for organizations to prepare, detect, and respond to malicious events.",
    modul: "Crises Recovery Strategies (CRS)",
    modulCode: "CRS",
    abschlusskompetenzen: "",
    fachkompetenzen: "F1: Tiefgehendes Verständnis der wichtigen Information Security-Prozesse BIA, BCM, DRP, BAK; F2: Krisen-Management-Strategien, SOC / CERT, IRP",
    methodenkompetenzen: "M1: Praktische Umsetzung von Prozessen",
    personalkompetenz: "P1: Team-Entwicklung",
    modulkurzbeschrieb: "Strategien zur Prävention, Vorbereitung, Erkennung und Reaktion auf Krisen, sowohl allgemein als auch spezifisch für IT-Vorfälle, werden diskutiert und praktisch in Krisen-Prozesse umgesetzt.",
    agenda: "SW 11 IRP & Forensik I: Incident Response als Prozess, Ziel, Strategie"
  },
  {
    id: 4,
    sectionHTB: "Preparation Stage (Part 1)",
    sentenceHTB: "For example, a data breach involving customer data must to be reported to law enforcement within a certain time threshold in accordance with GDPR.",
    modul: "High Tech Cybercrime & Law (HTCLAW)",
    modulCode: "HTCLAW",
    abschlusskompetenzen: "",
    fachkompetenzen: "Analysekompetenz: Problemfelder rund um strafbares Verhalten im digitalen Bereich erkennen.",
    methodenkompetenzen: "Analysekompetenz: Erkennen und Formulieren von Notwendigkeiten in bestimmten Unternehmungen und Prioritäten setzen im betrieblichen Umgang mit präventiven Massnahmen...",
    personalkompetenz: "Auftrittskompetenz: Sicheres persönliches und schriftliches Auftreten zu rechtlichen Fragen im Cyberstrafrecht.",
    modulkurzbeschrieb: "Das Fach legt die juristischen Grundlagen für Techniker und zeigt im Rahmen einfacher Beispiele auf, wo Grenzen der Technologie und des Rechts bestehen.",
    agenda: "SW 10 Forensik I: Beweisaufnahme in Ermittlung und Strafverfahren."
  },
  {
    id: 5,
    sectionHTB: "Preparation Stage (Part 2)",
    sentenceHTB: "Perform continuous vulnerability scans of our environment and remediate at least the 'High' and 'Critical' vulnerabilities that are discovered.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Für das SOC relevante Datenquellen kennen/erkennen können",
    methodenkompetenzen: "Analytisch Vorgehen bei der Verarbeitung von Informationen zur Erkennung und Einschätzung von Problemsituationen",
    personalkompetenz: "Selbständiges und genaues Arbeiten und Recherchieren",
    modulkurzbeschrieb: "SOC Modul bereitet auf die Tätigkeit im SOC vor, sowohl zum Verstehen der Technologien wie auch Prozesse und der Aufteilung der Rollen.",
    agenda: "SW 5 Vulnerability Management"
  },
  {
    id: 6,
    sectionHTB: "Detection & Analysis Stage (Part 1)",
    sentenceHTB: "Detection at the endpoint level (using antivirus systems, endpoint detection & response systems, etc.).",
    modul: "Mobile, Cloud & IoT Forensics (MCIF)",
    modulCode: "MCIF",
    abschlusskompetenzen: "",
    fachkompetenzen: "Die Studierenden verstehen Mobile Devices, IoT-Geräte & Cloud-Dienste als Spurenquellen.",
    methodenkompetenzen: "",
    personalkompetenz: "Die Studierenden können gezielte Empfehlungen abgeben für Ermittlungsfragen bezüglich Mobile, IoT und Cloud.",
    modulkurzbeschrieb: "Smartphones sind eine der wichtigsten Spurenquellen in polizeilichen Ermittlungen geworden... IoT-Geräte sind die Spurenträger und Angriffsziele der Zukunft.",
    agenda: "SW 1 Einführung Mobile & IoT: Definition Mobile & IoT als Spurenträger"
  },
  {
    id: 7,
    sectionHTB: "Detection & Analysis Stage (Part 2)",
    sentenceHTB: "Once the data has been collected, it is time to analyze it... Malware analysis and disk forensics are the most common examination types.",
    modul: "Malware Lab (MALWLAB)",
    modulCode: "MALWLAB",
    abschlusskompetenzen: "",
    fachkompetenzen: "Die Studierenden kennen Theorie und Anwendung statischer und dynamischer Analysetechniken zur Extraktion relevanter Informationen aus Malware.",
    methodenkompetenzen: "Die Studierenden sind in der Lage, Malware selbstständig zu klassifizieren und analysieren.",
    personalkompetenz: "Die Studierenden können Wissenslücken selbstständig identifizieren und beheben.",
    modulkurzbeschrieb: "Die Analyse von Malware, d.h. der Prozess aus Schadsoftware wichtige Informationen über ihre Absicht, Verwendung und Funktionsweise zu extrahieren, ist eine essentielle Fähigkeit in der IT-Sicherheit...",
    agenda: "SW 1 Einführung in Malwareanalyse: Klassifikation und Analysemethoden"
  },
  {
    id: 8,
    sectionHTB: "Detection & Analysis Stage (Part 2)",
    sentenceHTB: "Once the data has been collected, it is time to analyze it... Malware analysis and disk forensics are the most common examination types.",
    modul: "Computer Forensic (CF)",
    modulCode: "CF",
    abschlusskompetenzen: "Die Studierenden kennen die Funktionsweise von Dateisystemen sowie die Möglichkeiten im Rahmen von forensischen Analysen.",
    fachkompetenzen: "",
    methodenkompetenzen: "Die Studierenden können eine forensische Analyse eines Computersystems durchführen.",
    personalkompetenz: "Die Studierenden können Resultate aus verschiedenen Quellen in kohärenter Form präsentieren.",
    modulkurzbeschrieb: "Dieses Modul vermittelt grundlegende Kenntnisse der Computer-Forensik. Artefakte von Windows- und MacOS-Systemen und die Strukturen typischer Dateiformate werden behandelt.",
    agenda: "SW 5 Disk Forensik: Carving Dateistrukturen, File Headers"
  },
  {
    id: 9,
    sectionHTB: "Containment, Eradication, and Recovery Stage",
    sentenceHTB: "In the recovery stage, we bring systems back to normal operation.",
    modul: "Crises Recovery Strategies (CRS)",
    modulCode: "CRS",
    abschlusskompetenzen: "",
    fachkompetenzen: "F1: Tiefgehendes Verständnis der wichtigen Information Security-Prozesse BIA, BCM, DRP, BAK",
    methodenkompetenzen: "M1: Praktische Umsetzung von Prozessen",
    personalkompetenz: "P1: Team-Entwicklung",
    modulkurzbeschrieb: "NotebookLM Comment: Überschneidung in Bezug auf die Wiederanlaufplanung (Recovery).",
    agenda: "SW 7 BCM & DRP V - DRP & BAK: Vorbereitung und Planung, Wiederanlauf-Pläne, Backup-Konzepte"
  },
  {
    id: 10,
    sectionHTB: "Post-Incident Activity Stage",
    sentenceHTB: "The final report is a crucial part of the entire process... Such reports can eventually provide us with measurable results.",
    modul: "Grundlagen der Digitalen Forensik (DFF)",
    modulCode: "DFF",
    abschlusskompetenzen: "",
    fachkompetenzen: "Die Studierenden kennen wichtige Konzepte der Forensik und können sie in konkreten Fällen anwenden.",
    methodenkompetenzen: "",
    personalkompetenz: "Die Studierenden haben ein Verständnis für die Berufskultur der Forensik",
    modulkurzbeschrieb: "Konzepte der allgemeinen und der digitalen Forensik erlauben den Studierenden wichtige Aspekte eines Falles zu identifizieren und relevante Fragen zu stellen.",
    agenda: "SW 7 Reporting: Berichtsformen, Berichtsstrukturen, Dos and Don'ts"
  },
  {
    id: 11,
    sectionHTB: "Analysis of Insight Nexus Breach",
    sentenceHTB: "During Active Directory enumeration, they found that a Windows 10 machine (DEV-021) had a publicly exposed RDP port... The attacker took RDP directly into this machine using the newly created Domain Administrator account.",
    modul: "Cyber Defence (CYBER)",
    modulCode: "CYBER",
    abschlusskompetenzen: "",
    fachkompetenzen: "Angriff und Foothold selbständig durchführen",
    methodenkompetenzen: "Cyber-Kill Chain anwenden",
    personalkompetenz: "Verantwortungsvoller Umgang im Cyberspace",
    modulkurzbeschrieb: "Im Modul \"Cyber\" konzentrieren wir uns auf die grundlegenden Aspekte des ethischen Hackings entlang der Cyber-Kill Chain.",
    agenda: "SW 9 Übung: Phase 3 Lab: Eindringen Firma"
  },
  {
    id: 12,
    sectionHTB: "Skills Assessment",
    sentenceHTB: "Task 1: Additionally, you are provided with some event log files (i.e., logs-wazuh.zip). One of the tasks is to decode some PowerShell commands and extract IOCs from them.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Verarbeitung der im SOC anfallenden Daten.",
    methodenkompetenzen: "Analytisch Vorgehen bei der Verarbeitung von Informationen zur Erkennung und Einschätzung von Problemsituationen",
    personalkompetenz: "Selbständiges und genaues Arbeiten und Recherchieren",
    modulkurzbeschrieb: "Auf die Sammlung, Verdichtung und Auswertung der Daten sowie den Einsatz von Technologien wie Machine Learning und Artificial Intelligence wird im Rahmen der Automatisierung praxisorientiert eingegangen.",
    agenda: "SW 3 All about Data: praktische Übungen mit verschiedenen Datenquellen (Windows, Linux, Netzwerkkomponenten, Quellen im Internet)"
  }
];
