const HTB_DATA = [
  // ==========================================
  // HTB Modul 1 - Incident Handling Process
  // ==========================================
  {
    id: 1,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Incident Handling",
    sentenceHTB: "Incident handling is a clearly defined set of procedures for managing and responding to security incidents in a computer or network environment.",
    modul: "Angewandte Incident Response und IT Forensik (IRFORENSIC)",
    modulCode: "IRFORENSIC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Wissen wie bei einem Incident vorzugehen ist; Analysemöglichkeiten zum Auffinden des Angreifers",
    methodenkompetenzen: "Analytisches Vorgehen, um Angreifer in Systemen zu finden; Einleiten von Massnahmen, um Angreifer auszusperren; Effizienter Einsatz von Tools",
    personalkompetenz: "Analytisches und Systematisches Vorgehen",
    modulkurzbeschrieb: "Hacker benutzen ausgefeilte Techniken, um in Systeme einzudringen und diese zu kompromittieren. Die Reaktion, die Identifizierung sowie das Sicherstellen von Beweisen ist elementar.",
    agenda: "SW 1 Einführung: Incident Management, Incident Response"
  },
  {
    id: 2,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Cyber Kill Chain",
    sentenceHTB: "The cyber kill chain consists of seven different stages... Recon, Weaponize, Deliver, Exploit, Install, C&C, Action.",
    modul: "Cyber Defence (CYBER)",
    modulCode: "CYBER",
    abschlusskompetenzen: "",
    fachkompetenzen: "Information Gathering selbständig durchführen; Scanning selbständig durchführen; Angriff und Foothold selbständig durchführen",
    methodenkompetenzen: "Cyber-Kill Chain anwenden",
    personalkompetenz: "Verantwortungsvoller Umgang im Cyberspace",
    modulkurzbeschrieb: "Im Modul \"Cyber\" konzentrieren wir uns auf die grundlegenden Aspekte des ethischen Hackings entlang der Cyber-Kill Chain.",
    agenda: "SW 5 Kill Chain: Cyber Kill Chain, Rootkits, Penetration Testing Report"
  },
  {
    id: 3,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Incident Handling Process Overview",
    sentenceHTB: "The Incident Handling Process defines a capability for organizations to prepare, detect, and respond to malicious events.",
    modul: "Crises Recovery Strategies (CRS)",
    modulCode: "CRS",
    abschlusskompetenzen: "",
    fachkompetenzen: "F1: Tiefgehendes Verständnis der wichtigen Information Security-Prozesse BIA, BCM, DRP, BAK; F2: Krisen-Management-Strategien, SOC / CERT, IRP",
    methodenkompetenzen: "M1: Praktische Umsetzung von Prozessen",
    personalkompetenz: "P1: Team-Entwicklung",
    modulkurzbeschrieb: "Strategien zur Prävention, Vorbereitung, Erkennung und Reaktion auf Krisen, sowohl allgemein als auch spezifisch für IT-Vorfälle, werden diskutiert und praktisch in Krisen-Prozesse umgesetzt.",
    agenda: "SW 11 IRP & Forensik I: Incident Response als Prozess, Ziel, Strategie"
  },
  {
    id: 4,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Preparation Stage (Part 1)",
    sentenceHTB: "For example, a data breach involving customer data must to be reported to law enforcement within a certain time threshold in accordance with GDPR.",
    modul: "High Tech Cybercrime & Law (HTCLAW)",
    modulCode: "HTCLAW",
    abschlusskompetenzen: "",
    fachkompetenzen: "Analysekompetenz: Problemfelder rund um strafbares Verhalten im digitalen Bereich erkennen.",
    methodenkompetenzen: "Analysekompetenz: Erkennen und Formulieren von Notwendigkeiten in bestimmten Unternehmungen und Prioritäten setzen im betrieblichen Umgang mit präventiven Massnahmen...",
    personalkompetenz: "Auftrittskompetenz: Sicheres persönliches und schriftliches Auftreten zu rechtlichen Fragen im Cyberstrafrecht.",
    modulkurzbeschrieb: "Das Fach legt die juristischen Grundlagen für Techniker und zeigt im Rahmen einfacher Beispiele auf, wo Grenzen der Technologie und des Rechts bestehen.",
    agenda: "SW 10 Forensik I: Beweisaufnahme in Ermittlung und Strafverfahren."
  },
  {
    id: 5,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Preparation Stage (Part 2)",
    sentenceHTB: "Perform continuous vulnerability scans of our environment and remediate at least the 'High' and 'Critical' vulnerabilities that are discovered.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Für das SOC relevante Datenquellen kennen/erkennen können",
    methodenkompetenzen: "Analytisch Vorgehen bei der Verarbeitung von Informationen zur Erkennung und Einschätzung von Problemsituationen",
    personalkompetenz: "Selbständiges und genaues Arbeiten und Recherchieren",
    modulkurzbeschrieb: "SOC Modul bereitet auf die Tätigkeit im SOC vor, sowohl zum Verstehen der Technologien wie auch Prozesse und der Aufteilung der Rollen.",
    agenda: "SW 5 Vulnerability Management"
  },
  {
    id: 6,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Detection & Analysis Stage (Part 1)",
    sentenceHTB: "Detection at the endpoint level (using antivirus systems, endpoint detection & response systems, etc.).",
    modul: "Mobile, Cloud & IoT Forensics (MCIF)",
    modulCode: "MCIF",
    abschlusskompetenzen: "",
    fachkompetenzen: "Die Studierenden verstehen Mobile Devices, IoT-Geräte & Cloud-Dienste als Spurenquellen.",
    methodenkompetenzen: "",
    personalkompetenz: "Die Studierenden können gezielte Empfehlungen abgeben für Ermittlungsfragen bezüglich Mobile, IoT und Cloud.",
    modulkurzbeschrieb: "Smartphones sind eine der wichtigsten Spurenquellen in polizeilichen Ermittlungen geworden... IoT-Geräte sind die Spurenträger und Angriffsziele der Zukunft.",
    agenda: "SW 1 Einführung Mobile & IoT: Definition Mobile & IoT als Spurenträger"
  },
  {
    id: 7,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Detection & Analysis Stage (Part 2)",
    sentenceHTB: "Once the data has been collected, it is time to analyze it... Malware analysis and disk forensics are the most common examination types.",
    modul: "Malware Lab (MALWLAB)",
    modulCode: "MALWLAB",
    abschlusskompetenzen: "",
    fachkompetenzen: "Die Studierenden kennen Theorie und Anwendung statischer und dynamischer Analysetechniken zur Extraktion relevanter Informationen aus Malware.",
    methodenkompetenzen: "Die Studierenden sind in der Lage, Malware selbstständig zu klassifizieren und analysieren.",
    personalkompetenz: "Die Studierenden können Wissenslücken selbstständig identifizieren und beheben.",
    modulkurzbeschrieb: "Die Analyse von Malware, d.h. der Prozess aus Schadsoftware wichtige Informationen über ihre Absicht, Verwendung und Funktionsweise zu extrahieren, ist eine essentielle Fähigkeit in der IT-Sicherheit...",
    agenda: "SW 1 Einführung in Malwareanalyse: Klassifikation und Analysemethoden"
  },
  {
    id: 8,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Detection & Analysis Stage (Part 2)",
    sentenceHTB: "Once the data has been collected, it is time to analyze it... Malware analysis and disk forensics are the most common examination types.",
    modul: "Computer Forensic (CF)",
    modulCode: "CF",
    abschlusskompetenzen: "Die Studierenden kennen die Funktionsweise von Dateisystemen sowie die Möglichkeiten im Rahmen von forensischen Analysen.",
    fachkompetenzen: "",
    methodenkompetenzen: "Die Studierenden können eine forensische Analyse eines Computersystems durchführen.",
    personalkompetenz: "Die Studierenden können Resultate aus verschiedenen Quellen in kohärenter Form präsentieren.",
    modulkurzbeschrieb: "Dieses Modul vermittelt grundlegende Kenntnisse der Computer-Forensik. Artefakte von Windows- und MacOS-Systemen und die Strukturen typischer Dateiformate werden behandelt.",
    agenda: "SW 5 Disk Forensik: Carving Dateistrukturen, File Headers"
  },
  {
    id: 9,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Containment, Eradication, and Recovery Stage",
    sentenceHTB: "In the recovery stage, we bring systems back to normal operation.",
    modul: "Crises Recovery Strategies (CRS)",
    modulCode: "CRS",
    abschlusskompetenzen: "",
    fachkompetenzen: "F1: Tiefgehendes Verständnis der wichtigen Information Security-Prozesse BIA, BCM, DRP, BAK",
    methodenkompetenzen: "M1: Praktische Umsetzung von Prozessen",
    personalkompetenz: "P1: Team-Entwicklung",
    modulkurzbeschrieb: "NotebookLM Comment: Überschneidung in Bezug auf die Wiederanlaufplanung (Recovery).",
    agenda: "SW 7 BCM & DRP V - DRP & BAK: Vorbereitung und Planung, Wiederanlauf-Pläne, Backup-Konzepte"
  },
  {
    id: 10,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Post-Incident Activity Stage",
    sentenceHTB: "The final report is a crucial part of the entire process... Such reports can eventually provide us with measurable results.",
    modul: "Grundlagen der Digitalen Forensik (DFF)",
    modulCode: "DFF",
    abschlusskompetenzen: "",
    fachkompetenzen: "Die Studierenden kennen wichtige Konzepte der Forensik und können sie in konkreten Fällen anwenden.",
    methodenkompetenzen: "",
    personalkompetenz: "Die Studierenden haben ein Verständnis für die Berufskultur der Forensik",
    modulkurzbeschrieb: "Konzepte der allgemeinen und der digitalen Forensik erlauben den Studierenden wichtige Aspekte eines Falles zu identifizieren und relevante Fragen zu stellen.",
    agenda: "SW 7 Reporting: Berichtsformen, Berichtsstrukturen, Dos and Don'ts"
  },
  {
    id: 11,
    htbModule: 1,
    matchType: "green",
    sectionHTB: "Analysis of Insight Nexus Breach",
    sentenceHTB: "During Active Directory enumeration, they found that a Windows 10 machine (DEV-021) had a publicly exposed RDP port... The attacker took RDP directly into this machine using the newly created Domain Administrator account.",
    modul: "Cyber Defence (CYBER)",
    modulCode: "CYBER",
    abschlusskompetenzen: "",
    fachkompetenzen: "Angriff und Foothold selbständig durchführen",
    methodenkompetenzen: "Cyber-Kill Chain anwenden",
    personalkompetenz: "Verantwortungsvoller Umgang im Cyberspace",
    modulkurzbeschrieb: "Im Modul \"Cyber\" konzentrieren wir uns auf die grundlegenden Aspekte des ethischen Hackings entlang der Cyber-Kill Chain.",
    agenda: "SW 9 Übung: Phase 3 Lab: Eindringen Firma"
  },
  {
    id: 12,
    htbModule: 1,
    matchType: "yellow",
    sectionHTB: "Skills Assessment",
    sentenceHTB: "Task 1: Additionally, you are provided with some event log files (i.e., logs-wazuh.zip). One of the tasks is to decode some PowerShell commands and extract IOCs from them.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Verarbeitung der im SOC anfallenden Daten.",
    methodenkompetenzen: "Analytisch Vorgehen bei der Verarbeitung von Informationen zur Erkennung und Einschätzung von Problemsituationen",
    personalkompetenz: "Selbständiges und genaues Arbeiten und Recherchieren",
    modulkurzbeschrieb: "Auf die Sammlung, Verdichtung und Auswertung der Daten sowie den Einsatz von Technologien wie Machine Learning und Artificial Intelligence wird im Rahmen der Automatisierung praxisorientiert eingegangen.",
    agenda: "SW 3 All about Data: praktische Übungen mit verschiedenen Datenquellen (Windows, Linux, Netzwerkkomponenten, Quellen im Internet)"
  },

  // ==========================================
  // HTB Modul 2 - Security Monitoring & SIEM Fundamentals
  // ==========================================
  {
    id: 13,
    htbModule: 2,
    matchType: "green",
    sectionHTB: "Section 1: SIEM Definition & Fundamentals",
    sentenceHTB: "SIEM combines security information management (SIM) and security event management (SEM) to provide real-time analysis of security alerts generated by applications and network hardware.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Für das SOC relevante Datenquellen kennen/erkennen können; Verarbeitung der im SOC anfallenden Daten.",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Das SOC-Modul bereitet auf die Tätigkeit im SOC vor, sowohl zum Verstehen der Technologien wie auch der Prozesse und der Aufteilung der Rollen.",
    agenda: "SW 4: IDS (NIDS & HIDS) Vergleich mit SIEM, Gemeinsamkeiten und Unterschied"
  },
  {
    id: 14,
    htbModule: 2,
    matchType: "red",
    sectionHTB: "Section 2: Introduction To The Elastic Stack",
    sentenceHTB: "The Elastic Stack (ELK Stack) is a collection of three open-source products—Elasticsearch, Logstash, and Kibana—designed to help users search, analyze, and visualize data from any source.",
    modul: "Kein HSLU-Modul",
    modulCode: "-",
    abschlusskompetenzen: "",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Für diesen Bereich wurde in den HSLU-Modulkurzbeschrieben keine inhaltliche Überschneidung gefunden.",
    agenda: "-"
  },
  {
    id: 15,
    htbModule: 2,
    matchType: "green",
    sectionHTB: "Section 3: SOC Definition & Fundamentals",
    sentenceHTB: "A Security Operations Center (SOC) is a centralized unit that deals with security issues on an organizational and technical level.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "SOC Modul bereitet auf die Tätigkeit im SOC vor, sowohl zum Verstehen der Technologien wie auch Prozesse und der Aufteilung der Rollen.",
    agenda: "SW 1: Einführung ins SOC: Theorie, Aufgaben, Organisation, Rollen, Prozesse, Architektur..."
  },
  {
    id: 16,
    htbModule: 2,
    matchType: "green",
    sectionHTB: "Section 3: SOC Definition & Fundamentals",
    sentenceHTB: "A Security Operations Center (SOC) is a centralized unit that deals with security issues on an organizational and technical level.",
    modul: "Crises Recovery Strategies (CRS)",
    modulCode: "CRS",
    abschlusskompetenzen: "",
    fachkompetenzen: "F2: Krisen-Management-Strategien, SOC / CERT, IRP",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Strategien zur Prävention, Vorbereitung, Erkennung und Reaktion auf Krisen, sowohl allgemein als auch spezifisch für IT-Vorfälle.",
    agenda: "SW 8: SOC - Teil 1: Ziele und Strategie, Anforderungen, People, Prozesse"
  },
  {
    id: 17,
    htbModule: 2,
    matchType: "red",
    sectionHTB: "Section 4: MITRE ATT&CK & Security Operations",
    sentenceHTB: "MITRE ATT&CK is a globally-accessible knowledge base of adversary tactics and techniques based on real-world observations.",
    modul: "Kein HSLU-Modul",
    modulCode: "-",
    abschlusskompetenzen: "",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Für diesen Bereich wurde in den HSLU-Modulkurzbeschrieben keine inhaltliche Überschneidung gefunden.",
    agenda: "-"
  },
  {
    id: 18,
    htbModule: 2,
    matchType: "green",
    sectionHTB: "Section 5: SIEM Use Case Development",
    sentenceHTB: "Developing custom correlation rules and playbooks is essential to translate raw data log inputs into actionable threat alerts.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Auf die Sammlung, Verdichtung und Auswertung der Daten sowie den Einsatz von SOC Playbooks wird praxisorientiert eingegangen.",
    agenda: "SW 13: SOC Playbooks: Theorie & Lab - die Antwort auf die Frage wie gross ist das Problem und wer ist involviert. Entwickeln von Playbooks (Malware, Phishing, ...)"
  },
  {
    id: 19,
    htbModule: 2,
    matchType: "red",
    sectionHTB: "Section 6-9: SIEM Visualization Examples",
    sentenceHTB: "Creating visual maps, dashboards, and graphs inside Kibana to represent connection flows, geographical alerts, and protocol data.",
    modul: "Kein HSLU-Modul",
    modulCode: "-",
    abschlusskompetenzen: "",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Für diesen Bereich wurde in den HSLU-Modulkurzbeschrieben keine inhaltliche Überschneidung gefunden.",
    agenda: "-"
  },
  {
    id: 20,
    htbModule: 2,
    matchType: "green",
    sectionHTB: "Section 10: The Triaging Process",
    sentenceHTB: "Triage is the process of examining and prioritizing security alerts to filter out false positives and isolate true incidents.",
    modul: "Angewandte Incident Response und IT Forensik (IRFORENSIC)",
    modulCode: "IRFORENSIC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Wissen wie bei einem Incident vorzugehen ist",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Hacker benutzen ausgefeilte Techniken. Die Reaktion und Identifizierung eines Incidents ist elementar.",
    agenda: "SW 1 Einführung: Incident Management, Incident Response"
  },
  {
    id: 21,
    htbModule: 2,
    matchType: "green",
    sectionHTB: "Section 10: The Triaging Process",
    sentenceHTB: "Triage is the process of examining and prioritizing security alerts to filter out false positives and isolate true incidents.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Das SOC-Modul vermittelt die Grundlagen, wie bei einem gemeldeten Sicherheitsvorfall umzugehen ist.",
    agenda: "SW 11: Incident Response: Theorie (& Lab) was ist zu tun wenn es eingeschlagen hat. Best Practice fürs Vorgehen und Clean-Up"
  },
  {
    id: 22,
    htbModule: 2,
    matchType: "yellow",
    sectionHTB: "Section 11: Skills Assessment",
    sentenceHTB: "Perform a security analysis on a live dataset inside ELK stack, triage real alert triggers, and isolate malicious traffic patterns.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Verarbeitung, Analyse und Triage von Vorfällen im praktischen Lab.",
    agenda: "SW 9/10: praktisches Arbeiten im SOC II/III: Theorie & Lab Simulation mit Sentinel, Detection Lab, atomic red team, ..."
  },

  // ==========================================
  // HTB Modul 3 - Windows Event Logs & Finding Evil
  // ==========================================
  {
    id: 23,
    htbModule: 3,
    matchType: "green",
    sectionHTB: "Windows Event Logs",
    sentenceHTB: "Windows Event Logs store system, security, and application logs which are crucial for forensic tracking of suspicious local and remote actions.",
    modul: "Computer Forensic (CF)",
    modulCode: "CF",
    abschlusskompetenzen: "Die Studierenden kennen die Funktionsweise von Dateisystemen sowie die Möglichkeiten im Rahmen von forensischen Analysen.",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Artefakte von Windows- und MacOS-Systemen und die Strukturen typischer Dateiformate (inkl. Logfiles) werden behandelt.",
    agenda: "SW 6 Windows-Artefakte: NTFS, $MFT, Registry-Hives, Prefetch, Logfiles"
  },
  {
    id: 24,
    htbModule: 3,
    matchType: "green",
    sectionHTB: "Windows Event Logs",
    sentenceHTB: "Windows Event Logs store system, security, and application logs which are crucial for forensic tracking of suspicious local and remote actions.",
    modul: "Angewandte Incident Response und IT Forensik (IRFORENSIC)",
    modulCode: "IRFORENSIC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Analysemöglichkeiten zum Auffinden des Angreifers",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Die Analyse von infizierten Systemen und Log-Analysen bilden einen Schwerpunkt der Laborarbeiten.",
    agenda: "SW 9 Network und Log Analysis: Theorie + Labor: Network Analysis, Log Analysis"
  },
  {
    id: 25,
    htbModule: 3,
    matchType: "green",
    sectionHTB: "Windows Event Logs",
    sentenceHTB: "Windows Event Logs store system, security, and application logs which are crucial for forensic tracking of suspicious local and remote actions.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Für das SOC relevante Datenquellen kennen/erkennen können",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Auf die Sammlung, Verdichtung und Auswertung der Daten aus Windows- und Linux-Systemen wird praktisch eingegangen.",
    agenda: "SW 3 All about Data: praktische Übungen mit verschiedenen Datenquellen (Windows, Linux, Netzwerkkomponenten, Quellen im Internet)"
  },
  {
    id: 26,
    htbModule: 3,
    matchType: "green",
    sectionHTB: "Analyzing Evil With Sysmon & Event Logs",
    sentenceHTB: "Using Microsoft Sysmon to enrich logs with process creation (Event ID 1), network connections (Event ID 3), and detect adversary activity.",
    modul: "Security Operation Center Issues (SOC)",
    modulCode: "SOC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Für das SOC relevante Datenquellen kennen/erkennen können; Verarbeitung der im SOC anfallenden Daten.",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Praktisches Arbeiten im SOC-Labor zur Simulation und Erkennung von Angriffen mit sysmon und SIEM-Tools.",
    agenda: "SW 9 praktisches Arbeiten im SOC II: Theorie & Lab Simulation mit Sentinel, Detection Lab, atomic red team, sysmon ..."
  },
  {
    id: 27,
    htbModule: 3,
    matchType: "red",
    sectionHTB: "Event Tracing for Windows (ETW)",
    sentenceHTB: "Event Tracing for Windows (ETW) is a kernel-level tracing facility that lets you log software events to a file or consume them in real-time.",
    modul: "Kein HSLU-Modul",
    modulCode: "-",
    abschlusskompetenzen: "",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Für diesen Bereich wurde in den HSLU-Modulkurzbeschrieben keine inhaltliche Überschneidung gefunden.",
    agenda: "-"
  },
  {
    id: 28,
    htbModule: 3,
    matchType: "red",
    sectionHTB: "Tapping Into ETW",
    sentenceHTB: "Consuming kernel traces directly using custom telemetry sensors, bypassing standard Event Viewer mechanisms.",
    modul: "Kein HSLU-Modul",
    modulCode: "-",
    abschlusskompetenzen: "",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Für diesen Bereich wurde in den HSLU-Modulkurzbeschrieben keine inhaltliche Überschneidung gefunden.",
    agenda: "-"
  },
  {
    id: 29,
    htbModule: 3,
    matchType: "red",
    sectionHTB: "Get-WinEvent",
    sentenceHTB: "Using PowerShell's Get-WinEvent cmdlet to query and extract structural security telemetry data from Windows event logs.",
    modul: "Kein HSLU-Modul",
    modulCode: "-",
    abschlusskompetenzen: "",
    fachkompetenzen: "",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Für diesen Bereich wurde in den HSLU-Modulkurzbeschrieben keine inhaltliche Überschneidung gefunden.",
    agenda: "-"
  },
  {
    id: 30,
    htbModule: 3,
    matchType: "yellow",
    sectionHTB: "Skills Assessment",
    sentenceHTB: "Analyze Windows Event log logs from a compromised machine, track user logins (Event ID 4624), process creation, and malicious PowerShell triggers.",
    modul: "Angewandte Incident Response und IT Forensik (IRFORENSIC)",
    modulCode: "IRFORENSIC",
    abschlusskompetenzen: "",
    fachkompetenzen: "Wissen wie bei einem Incident vorzugehen ist; Analysemöglichkeiten zum Auffinden des Angreifers",
    methodenkompetenzen: "",
    personalkompetenz: "",
    modulkurzbeschrieb: "Praktisches Lab zur Analyse infizierter Systeme und Logdateien eines realen Incidents.",
    agenda: "SW 14 Infected System Lab: Labor Analyse von infizierten Systemen"
  }
];
